// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR7f2D66fWhL1jEzykfhp5wzDeN2_SxRU',
    appId: '1:909055223147:web:072d0bb691ca7562eb582e',
    messagingSenderId: '909055223147',
    projectId: 'sumfit-app-20251101165453',
    authDomain: 'sumfit-app-20251101165453.firebaseapp.com',
    storageBucket: 'sumfit-app-20251101165453.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBwR_cuG2Qq4DezbGrj9qJC1Q1bC92aaA',
    appId: '1:909055223147:android:8e23b7dfe2d506eaeb582e',
    messagingSenderId: '909055223147',
    projectId: 'sumfit-app-20251101165453',
    storageBucket: 'sumfit-app-20251101165453.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh3QLUf4RRU1j7uw6FccPX_sjsj4iQlEo',
    appId: '1:909055223147:ios:2cf38e0ead980807eb582e',
    messagingSenderId: '909055223147',
    projectId: 'sumfit-app-20251101165453',
    storageBucket: 'sumfit-app-20251101165453.firebasestorage.app',
    iosBundleId: 'com.example.sumfit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh3QLUf4RRU1j7uw6FccPX_sjsj4iQlEo',
    appId: '1:909055223147:ios:2cf38e0ead980807eb582e',
    messagingSenderId: '909055223147',
    projectId: 'sumfit-app-20251101165453',
    storageBucket: 'sumfit-app-20251101165453.firebasestorage.app',
    iosBundleId: 'com.example.sumfit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR7f2D66fWhL1jEzykfhp5wzDeN2_SxRU',
    appId: '1:909055223147:web:46ff0efe4f9dcff3eb582e',
    messagingSenderId: '909055223147',
    projectId: 'sumfit-app-20251101165453',
    authDomain: 'sumfit-app-20251101165453.firebaseapp.com',
    storageBucket: 'sumfit-app-20251101165453.firebasestorage.app',
  );

}